backend:
  name: github
  repo: asheerrizvi/bilbos-diary

media_folder: content/assets
public_folder: ../assets

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    media_folder: ""
    public_folder: ""
    path: "{{foldername}}/index"
    fields:
      - { label: "Folder Name", name: "foldername", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
